### ISSUE TITLE
[Question] What is the reasonable speed?

### ISSUE THREAD

**Issue by burner1024** [morrownr/8821au-20210708#102]
Hi.
First off, thank you for the driver.
I'm using it with hostapd, providing a 5Ghz access point. Generally, `iwconfig` shows speed fluctuating in 250-400 Mb/s interval.
It's decent, but I wonder, is it as good as it reasonably gets, or I should look for a bottleneck somewhere?

**Comment by morrownr** [comment]
Hi @burner1024 

I have a speed comparison test that you can look at on the site Main Menu:

https://github.com/morrownr/USB-WiFi

Go to menu item 12.

While on the Main Menu, I recommend reading menu items 1 and 2. There is a lot of good information there for Linux users.

Let me know if you have any questions.

@morrownr

**Comment by burner1024** [comment]
Great, thank you!
