### ISSUE TITLE
Can you edit this script to add install on openwrt ability?

### ISSUE THREAD

**Issue by PriFak** [morrownr/8821au-20210708#104]
Hello, I have an Openwrt device on ARM arch but i cant install this driver  because dkms and headers doesn't exist on Openwrt. So can you modify script to add installing direct on openwrt or  by cross compilation?

**Comment by morrownr** [comment]
> can you modify script to add installing direct on openwrt or by cross compilation?

No. I use OpenWRT and use USB WiFi adapters with it. I don't use adapters that use Realtek out-of-kernel drivers as that is complicated to do and requires cross-compiling.

What I recommend to users who want to use USB WiFi adapters with OpenWRT is for them to get an adapter that uses the already existing drivers that provide capabilities all the way up to AXE3000. The chipsets that are supported include the mt7921au, mt7612u and mt7610u. I have a list of "Plug and Play" adapter. The list is shown as menu item 2 on the Main Main:

https://github.com/morrownr/USB-WiFi
