### ISSUE TITLE
dkms-make.sh (bad exit status :2) dkms build error:  10

### ISSUE THREAD

**Issue by Ciren1211** [morrownr/8821au-20210708#106]
Hello, I am on a le potato and running rasbian 11. I am a complete beginner to all of this and not sure why it is not working. Here is what it gave me when i ran the ./install-driver.sh
`ciren@raspberrypi:~/src/8821au-20210708 $ sudo ./install-driver.sh
: ---------------------------
: install-driver.sh v20230227
: aarch64 (architecture)
: 4/4 (in-use/total processing units)
: 1995696 (total system memory)
: 6.1.46-08797-g9c18484153bc (kernel version)
: gcc (Debian 10.2.1-6) 10.2.1 20210110
: dkms:2.8
: ---------------------------

Checking for previously installed drivers.
: ---------------------------

Starting installation.
Installing 8821au.conf to /etc/modprobe.d
The dkms installation routines are in use.
Copying source files to /usr/src/rtl8821au-5.12.5.2

Creating symlink /var/lib/dkms/rtl8821au/5.12.5.2/source ->
                 /usr/src/rtl8821au-5.12.5.2

DKMS: add completed.
The driver was added to dkms successfully.
: ---------------------------

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
./dkms-make.sh.......(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.46-08797-g9c18484153bc (aarch64)
Consult /var/lib/dkms/rtl8821au/5.12.5.2/build/make.log for more information.
An error occurred. dkms build error:  10
Please report this error.
Please copy all screen output and paste it into the problem report.
Run the following before reattempting installation.
$ sudo ./remove-driver.sh`

**Comment by morrownr** [comment]
Hi @Ciren1211 

I'll try to help.

> I am on a le potato and running rasbian 11

Can you explain what `le potato` is?

The rasbian is the very old name of the Rasberry Pi OS. Can you clarify what distro you are using?

Please run the following and post the results:

$ lsusb

> : 6.1.46-08797-g9c18484153bc (kernel version)
> : gcc (Debian 10.2.1-6) 10.2.1 20210110

The likely cause is shown in the above 2 lines. You are running kernel 6.1 which is likely compiled by gcc-12 but then the installed gcc is showing as gcc10. That is too big of a gap. The quickest fix is likely to install gcc-12:

$ sudo apt install gcc-12

Regards
