### ISSUE TITLE
how to compile as an external kernel module?

### ISSUE THREAD

**Issue by erophey7** [morrownr/8821au-20210708#110]
I tried this instruction: https://www.kernel.org/doc/Documentation/kbuild/modules.txt, but it didn’t work:

```
erophey7@compudahter-kubuntu:~/eblya/8821au-20210708$ make -C $HOME/eblya/android_kernel_xiaomi_lahaina/out M=$PWD ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CROSS_COMPILE=$TC_DIR/bin/llvm-

make: Entering directory '/home/erophey7/eblya/android_kernel_xiaomi_lahaina/out'
  Building modules, stage 2.
  MODPOST 0 modules
make: Leaving directory '/home/erophey7/eblya/android_kernel_xiaomi_lahaina/out'
```
Clang: [google clang-r450784d](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/android-arm64-deadpool-4.9-android13-tv/clang-r450784d/)
kernel: https://github.com/ghostrider-reborn/android_kernel_xiaomi_lahaina

**Comment by morrownr** [comment]
Hi @erophey7 

I have a lot of patches nearly ready to go it and one may help you out. Keep an eye out for newly merged patches.

**Comment by morrownr** [comment]
I've now merged a large set of patches that might help.
