### ISSUE TITLE
Support 8811CU Device

### ISSUE THREAD

**Issue by jay214128** [morrownr/8821au-20210708#13]
I can build the driver for the 8811AU device (CONFIG_RTL8821A=y), but I need to also build for the 8811CU part at the same time (CONFIG_RTL8821C=y).  When I also enable CONFIG_RTL8821C=y, the build fails with rt8821c.mk: No such file or directory.

Can you update the driver source to support the rtl8811CU part?

**Comment by morrownr** [comment]
Hi @jay214128 

You need to run:

$ sudo ./remove-driver.sh

.... to make sure things are cleaned up and then go to the following repo:

https://github.com/morrownr/8821cu

Regards

**Comment by morrownr** [comment]
Closing due to lack of reply.
