### ISSUE TITLE
 kernel 4.14.180

### ISSUE THREAD

**Issue by bilIgates** [morrownr/8821au-20210708#43]
does this support kernel 4.14.180

i made module 8821au.ko
without dkms

i am getting following error if i try to run

insmod /vendor/lib/modules/8821au.ko                                
insmod: failed to load /vendor/lib/modules/8821au.ko: Exec format error

 ./vendor/lib/modules/8821au.ko                                        
/system/bin/sh: ./vendor/lib/modules/8821au.ko: not executable: 64-bit ELF file

 modinfo ./vendor/lib/modules/8821au.ko                            
filename:       ./vendor/lib/modules/8821au.ko
license:        GPL
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
name:           8821au
vermagic:       4.14.180 SMP preempt mod_unload modversions aarch64

**Comment by bilIgates** [comment]
cat /proc/version
Linux version 4.14.180 (Android (7485623, based on r416183b1) clang version 12.0.7 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d708641d52d2f7ee), GNU ld (binutils-2.27-bd24d23f) 2.27.0.20170315)

device is redmi note 10 pro

**Comment by morrownr** [comment]
Android. 

This driver probably can work with Android but I am not the one to help as I have no experience with Android.

Regards
