### ISSUE TITLE
awus036acs and android/nethunter

### ISSUE THREAD

**Issue by iKoRk3** [morrownr/8821au-20210708#65]
Hi I have awus036acs and in kali linux this driver works great. Does it support android? I have nethunter and android 11 using kernel 4.14.290-agni-miatoll_kali-nethunter_v14.2-stable is there any way to get you driver into android/nethunter? thank you for your time and help

**Comment by morrownr** [comment]
Hi @iKoRk3 

>  Does it support android?

I'm confident that this driver can support Android. I've never had a need and don't know what needs to be done so it will take a little research on your end.

Nick
