### ISSUE TITLE
Debian 11 driver doesn't pick up usb wifi adapter

### ISSUE THREAD

**Issue by hman901** [morrownr/8821au-20210708#67]
uname -mr
5.10.0-20-amd64 x86_64
dkms status
rtl8821au, 5.12.5.2, 5.10.0-20-amd64, x86_64: installed
mokutil --sb-state
SecureBoot enabled
lsusb
Bus 001 Device 003: ID 2357:0120 TP-Link Archer T2U PLUS [RTL8821AU]
iw dev
phy#0
	Unnamed/non-netdev interface
		wdev 0x2
		addr 74:d8:3e:d0:42:f6
		type P2P-device
		txpower 0.00 dBm
	Interface wlp58s0
		ifindex 3
		wdev 0x1
		addr 74:d8:3e:d0:42:f6
		ssid Q_&_F.co
		type managed
		channel 6 (2437 MHz), width: 20 MHz, center1: 2437 MHz
		txpower 22.00 dBm

lsmod
Module                  Size  Used by
ctr                    16384  1
ccm                    20480  3
rfcomm                 94208  0
cmac                   16384  3
algif_hash             16384  1
algif_skcipher         16384  1
af_alg                 32768  6 algif_hash,algif_skcipher
bnep                   28672  2
squashfs               69632  0
btusb                  65536  0
btrtl                  28672  1 btusb
btbcm                  20480  1 btusb
btintel                32768  1 btusb
snd_soc_skl_hda_dsp    28672  5
intel_pmc_core_pltdrv    16384  0
snd_soc_hdac_hdmi      45056  1 snd_soc_skl_hda_dsp
intel_pmc_core         45056  0
bluetooth             753664  33 btrtl,btintel,btbcm,bnep,btusb,rfcomm
snd_hda_codec_hdmi     73728  1
snd_hda_codec_realtek   163840  1
jitterentropy_rng      16384  1
snd_hda_codec_generic    98304  1 snd_hda_codec_realtek
msr                    16384  0
x86_pkg_temp_thermal    20480  0
snd_soc_dmic           16384  1
parport_pc             40960  0
intel_powerclamp       20480  0
drbg                   40960  1
snd_sof_pci            24576  0
snd_sof_intel_byt      24576  1 snd_sof_pci
coretemp               20480  0
ppdev                  24576  0
snd_sof_intel_ipc      20480  1 snd_sof_intel_byt
snd_sof_intel_hda_common   102400  1 snd_sof_pci
snd_sof_xtensa_dsp     16384  2 snd_sof_intel_hda_common,snd_sof_intel_byt
snd_sof               139264  4 snd_sof_pci,snd_sof_intel_hda_common,snd_sof_intel_byt,snd_sof_intel_ipc
snd_sof_intel_hda      20480  1 snd_sof_intel_hda_common
kvm_intel             331776  0
ledtrig_audio          16384  2 snd_hda_codec_generic,snd_sof
snd_soc_skl           180224  0
mei_wdt                16384  0
lp                     20480  0
mei_hdcp               24576  0
parport                73728  3 parport_pc,lp,ppdev
iwlmvm                348160  0
snd_soc_hdac_hda       24576  2 snd_sof_intel_hda_common,snd_soc_skl
snd_hda_ext_core       36864  5 snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
intel_rapl_msr         20480  0
snd_soc_sst_ipc        20480  1 snd_soc_skl
snd_soc_sst_dsp        36864  1 snd_soc_skl
snd_soc_acpi_intel_match    45056  3 snd_sof_pci,snd_sof_intel_hda_common,snd_soc_skl
snd_soc_acpi           16384  4 snd_soc_acpi_intel_match,snd_sof_intel_hda_common,snd_sof_intel_byt,snd_soc_skl
kvm                   937984  1 kvm_intel
mac80211              995328  1 iwlmvm
snd_hda_intel          57344  0
irqbypass              16384  1 kvm
aes_generic            36864  0
snd_intel_dspcfg       28672  4 snd_hda_intel,snd_sof_pci,snd_sof_intel_hda_common,snd_soc_skl
libarc4                16384  1 mac80211
soundwire_intel        45056  2 snd_sof_intel_hda_common,snd_intel_dspcfg
soundwire_generic_allocation    16384  1 soundwire_intel
ghash_clmulni_intel    16384  0
binfmt_misc            24576  1
snd_soc_core          319488  8 soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl,snd_soc_dmic,snd_soc_skl_hda_dsp
iwlwifi               299008  1 iwlmvm
aesni_intel           372736  6
rapl                   20480  0
nls_ascii              16384  1
snd_compress           32768  1 snd_soc_core
nls_cp437              20480  1
soundwire_cadence      36864  1 soundwire_intel
intel_cstate           20480  0
snd_hda_codec         176128  6 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek,snd_soc_hdac_hda,snd_soc_skl_hda_dsp
vfat                   20480  1
crypto_simd            16384  1 aesni_intel
cryptd                 24576  3 crypto_simd,ghash_clmulni_intel
fat                    86016  1 vfat
cfg80211              983040  3 iwlmvm,iwlwifi,mac80211
intel_uncore          180224  0
glue_helper            16384  1 aesni_intel
uvcvideo              118784  0
snd_hda_core          110592  12 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_hda_codec_realtek,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda,snd_soc_skl_hda_dsp
videobuf2_vmalloc      20480  1 uvcvideo
videobuf2_memops       20480  1 videobuf2_vmalloc
snd_hwdep              16384  1 snd_hda_codec
videobuf2_v4l2         36864  1 uvcvideo
ansi_cprng             16384  0
soundwire_bus          94208  3 soundwire_intel,soundwire_generic_allocation,soundwire_cadence
videobuf2_common       65536  2 videobuf2_v4l2,uvcvideo
efi_pstore             16384  0
hp_wmi                 20480  0
iTCO_wdt               16384  0
intel_pmc_bxt          16384  1 iTCO_wdt
sparse_keymap          16384  1 hp_wmi
joydev                 28672  0
pcspkr                 16384  0
snd_pcm               143360  11 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_compress,snd_soc_core,snd_soc_skl,snd_hda_core
serio_raw              20480  0
iTCO_vendor_support    16384  1 iTCO_wdt
videodev              294912  3 videobuf2_v4l2,uvcvideo,videobuf2_common
intel_wmi_thunderbolt    20480  0
wmi_bmof               16384  0
ecdh_generic           16384  2 bluetooth
ee1004                 20480  0
watchdog               32768  2 iTCO_wdt,mei_wdt
mc                     61440  4 videodev,videobuf2_v4l2,uvcvideo,videobuf2_common
snd_timer              49152  1 snd_pcm
mei_me                 45056  2
tpm_crb                20480  0
snd                   110592  22 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_soc_hdac_hdmi,snd_compress,snd_soc_core,snd_pcm,snd_soc_skl_hda_dsp
mei                   139264  5 mei_wdt,mei_hdcp,mei_me
rfkill                 32768  9 hp_wmi,bluetooth,cfg80211
soundcore              16384  1 snd
hid_multitouch         32768  0
ecc                    36864  1 ecdh_generic
hid_sensor_als         20480  0
hid_sensor_trigger     20480  2 hid_sensor_als
hid_sensor_iio_common    20480  2 hid_sensor_trigger,hid_sensor_als
libaes                 16384  3 bluetooth,aesni_intel,aes_generic
industrialio_triggered_buffer    16384  1 hid_sensor_trigger
processor_thermal_device    28672  0
ucsi_acpi              16384  0
kfifo_buf              16384  1 industrialio_triggered_buffer
intel_rapl_common      28672  2 intel_rapl_msr,processor_thermal_device
typec_ucsi             49152  1 ucsi_acpi
intel_soc_dts_iosf     20480  1 processor_thermal_device
intel_pch_thermal      16384  0
industrialio           94208  4 industrialio_triggered_buffer,hid_sensor_trigger,kfifo_buf,hid_sensor_als
int3403_thermal        20480  0
typec                  61440  1 typec_ucsi
int340x_thermal_zone    16384  2 int3403_thermal,processor_thermal_device
tpm_tis                16384  0
tpm_tis_core           28672  1 tpm_tis
tpm                    73728  3 tpm_tis,tpm_crb,tpm_tis_core
rng_core               16384  1 tpm
evdev                  28672  21
acpi_pad              184320  0
int3400_thermal        20480  0
acpi_thermal_rel       16384  1 int3400_thermal
hp_wireless            16384  0
ac                     16384  0
loop                   40960  0
dm_crypt               57344  0
dm_mod                163840  1 dm_crypt
fuse                  167936  5
configfs               57344  1
efivarfs               16384  1
ip_tables              36864  0
x_tables               53248  1 ip_tables
autofs4                53248  2
ext4                  942080  1
crc16                  16384  2 bluetooth,ext4
mbcache                16384  1 ext4
jbd2                  151552  1 ext4
btrfs                1589248  0
blake2b_generic        20480  0
raid10                 65536  0
raid456               184320  0
async_raid6_recov      24576  1 raid456
async_memcpy           20480  2 raid456,async_raid6_recov
async_pq               20480  2 raid456,async_raid6_recov
async_xor              20480  3 async_pq,raid456,async_raid6_recov
async_tx               20480  5 async_pq,async_memcpy,async_xor,raid456,async_raid6_recov
xor                    24576  2 async_xor,btrfs
raid6_pq              122880  4 async_pq,btrfs,raid456,async_raid6_recov
libcrc32c              16384  2 btrfs,raid456
crc32c_generic         16384  0
raid1                  53248  0
raid0                  24576  0
multipath              20480  0
linear                 20480  0
md_mod                188416  6 raid1,raid10,raid0,linear,raid456,multipath
usbhid                 65536  0
hid_sensor_hub         24576  3 hid_sensor_trigger,hid_sensor_iio_common,hid_sensor_als
intel_ishtp_hid        28672  0
i915                 2772992  8
i2c_algo_bit           16384  1 i915
drm_kms_helper        278528  1 i915
nvme                   49152  3
hid_generic            16384  0
xhci_pci               20480  0
xhci_hcd              311296  1 xhci_pci
cec                    61440  2 drm_kms_helper,i915
e1000e                311296  0
usbcore               331776  5 xhci_hcd,usbhid,uvcvideo,btusb,xhci_pci
nvme_core             131072  5 nvme
crc32_pclmul           16384  0
drm                   626688  7 drm_kms_helper,i915
crc32c_intel           24576  3
t10_pi                 16384  1 nvme_core
crc_t10dif             20480  1 t10_pi
crct10dif_generic      16384  0
ptp                    32768  1 e1000e
crct10dif_pclmul       16384  1
psmouse               184320  0
thunderbolt           299008  0
i2c_i801               32768  0
i2c_hid                32768  0
intel_lpss_pci         24576  0
intel_ish_ipc          28672  0
intel_lpss             16384  1 intel_lpss_pci
pps_core               24576  1 ptp
intel_ishtp            61440  2 intel_ishtp_hid,intel_ish_ipc
i2c_smbus              20480  1 i2c_i801
crct10dif_common       16384  3 crct10dif_generic,crc_t10dif,crct10dif_pclmul
hid                   151552  6 i2c_hid,usbhid,hid_multitouch,hid_sensor_hub,intel_ishtp_hid,hid_generic
idma64                 20480  0
usb_common             16384  3 xhci_hcd,usbcore,uvcvideo
wmi                    36864  3 hp_wmi,intel_wmi_thunderbolt,wmi_bmof
battery                24576  0
video                  61440  1 i915
button                 24576  0

**Comment by morrownr** [comment]
Hi @hman901 

As I look over the info you posted, the thing that got my attention is:

SecureBoot enabled

This driver is certainly capable of working with SecureBoot but the installation scripts only set things up automatically for the distros that it knows how to support which includes all Ubuntu based distros.

The README.md file, the main screen, has info about SecureBoot in 3 places and the info in the FAQ gives a link that is about Debian. You can try the following first but if it does not work, please read the FAQ:

SecureBoot requires that the `openssl` and `mokutil` packages are installed so install them if they are not installed and run:

$ sudo mokutil --import /var/lib/dkms/mok.pub

After a reboot, see if the driver is used by the kernel.

Let me know. If you get it working, I'd like to add the info to the docs so that future Debian users have the info.

Nick

**Comment by hman901** [comment]
Thanks it work with SecureBoot disabled

sudo mokutil --import /var/lib/dkms/mok.pub
Failed to get file status, /var/lib/dkms/mok.pub
