### ISSUE TITLE
Driver is installed but adapter isn't detected.

### ISSUE THREAD

**Issue by chapati-soldier** [morrownr/8821au-20210708#69]
I'm using a TP-Link Archer T2U V3 and I'm running Fedora 37. The driver compiled and installed fine but the driver isn't still detected.

**Comment by morrownr** [comment]
There is a pinned issue called Problem Reporting Guidelines. Please read it.

**Comment by chapati-soldier** [comment]
I'm sorry, I got a Dell Latitude 3460 and I'm running Fedora 37 on kernel 6.1.8-200 and when I run the command given in the pinned command, I get `6.1.8-200.fc37.x86_64 x86_64
SecureBoot disabled
Bus 001 Device 002: ID 8087:8001 Intel Corp. Integrated Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 005: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 002 Device 006: ID 0cf3:e006 Qualcomm Atheros Communications Dell Wireless 1802 Bluetooth 4.0 LE
Bus 002 Device 003: ID 0bda:5683 Realtek Semiconductor Corp. Integrated_Webcam_HD
Bus 002 Device 002: ID 2357:011f TP-Link 802.11ac WLAN Adapter 
Bus 002 Device 009: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 002 Device 008: ID 18d1:4ee3 Google Inc. Nexus/Pixel Device (tether)
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
0: dell-wifi: Wireless LAN
	Soft blocked: no
	Hard blocked: yes
1: dell-bluetooth: Bluetooth
	Soft blocked: no
	Hard blocked: yes
2: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: yes
3: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
rtl8821au/5.12.5.2, 6.1.8-200.fc37.x86_64, x86_64: installed
phy#0
	Interface wlp6s0
		ifindex 3
		wdev 0x1
		addr 3a:b0:8e:08:82:8e
		type managed
		txpower 0.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcoltx-bytes	tx-packets
			0	0	0	0	0	0	0	00
global
country IN: DFS-UNSET
	(2402 - 2482 @ 40), (N/A, 20), (N/A)
	(5150 - 5250 @ 80), (N/A, 30), (N/A)
	(5250 - 5350 @ 80), (N/A, 24), (N/A)
	(5470 - 5725 @ 160), (N/A, 24), (N/A)
	(5725 - 5875 @ 80), (N/A, 30), (N/A)

phy#0
country 99: DFS-UNSET
	(2402 - 2472 @ 40), (N/A, 20), (N/A)
	(2457 - 2482 @ 40), (N/A, 20), (N/A), PASSIVE-SCAN
	(5140 - 5360 @ 80), (N/A, 30), (N/A), PASSIVE-SCAN
	(5460 - 5860 @ 80), (N/A, 30), (N/A), PASSIVE-SCAN
`

**Comment by sunwire** [comment]
I think you use the wrong driver. You have to use **8812au** instead of 8821au.

**Comment by morrownr** [comment]
The driver is correct but...

> 2: phy0: Wireless LAN
Soft blocked: no
Hard blocked: yes

Airplane mode is on. It is hardware airplane mode so there is a key, or key combination or button that you need to press to turn it off.

**Comment by chapati-soldier** [comment]
thank you this worked for me :)
